import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { UserProvider } from "@/context/userContext";
import { DeleteCardProvider } from "@/context/deleteCardContext";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rbt = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`bg-gray-200 flex flex-col min-h-screen ${rbt.className}`}>
        <UserProvider>
          <DeleteCardProvider>
            <Header />
            {children}
            <Footer />
          </DeleteCardProvider>
        </UserProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
